######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 21 23:51:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . includes/display includes/modules srcs/modules
INCLUDEPATH += . includes/modules

# Input
HEADERS += mainwindow.h \
           includes/display/IMonitorDisplay.hpp \
           includes/modules/Battery.hpp \
           includes/modules/Cpu.hpp \
           includes/modules/Date.hpp \
           includes/modules/IMonitorModule.hpp \
           includes/modules/NetworkLoad.hpp \
           includes/modules/Ram.hpp \
           includes/modules/System.hpp \
           includes/modules/User.hpp \
    ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           srcs/modules/Battery.cpp \
           srcs/modules/Cpu.cpp \
           srcs/modules/Date.cpp \
           srcs/modules/NetworkLoad.cpp \
           srcs/modules/Ram.cpp \
           srcs/modules/System.cpp \
           srcs/modules/User.cpp
